---
_extends: .github

repository:
  name: c-toxcore-hs
  description: C bindings to the Haskell implementation of the Tox protocol
  topics: toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - cirrus-ci
          - Codacy/PR Quality Review
          - code-review/reviewable
          - license/cla
          - WIP
