---
language: cpp
compiler: clang
dist: xenial
os: linux

before_install:
  - cd ..
  - git clone --depth=1 https://github.com/TokTok/toktok-stack
  - (cd toktok-stack && git submodule update --jobs=8 --init --depth=5 --recursive)
  - rm -rf toktok-stack/c-toxcore-hs
  - mv c-toxcore-hs toktok-stack/
  - cd toktok-stack/

install:
  - wget https://github.com/bazelbuild/bazel/releases/download/2.2.0/bazel-2.2.0-installer-linux-x86_64.sh
  - chmod +x bazel-2.2.0-installer-linux-x86_64.sh
  - ./bazel-2.2.0-installer-linux-x86_64.sh --user
  - echo 'build --jobs=4 --curses=no --verbose_failures' > $HOME/.bazelrc
  - echo 'build --config=linux' >> $HOME/.bazelrc
  - echo "build --config=$CC" >> $HOME/.bazelrc
  - echo 'build --config=remote' >> $HOME/.bazelrc

script:
  - bazel test //c-toxcore-hs/...
