---
language: cpp
compiler: clang
dist: xenial
os: linux

before_install:
  - cd ..
  - git clone --depth=1 https://github.com/TokTok/toktok-stack
  - (cd toktok-stack && git submodule update --jobs=8 --init --depth=5 --recursive)
  - rm -rf toktok-stack/c-toxcore-hs
  - mv c-toxcore-hs toktok-stack/
  - cd toktok-stack/

install:
  - tools/setup-bazel
  - tools/setup-ci

script:
  - bazel test //c-toxcore-hs/...
